<a href="https://colab.research.google.com/github/ireneminhee/BKBS/blob/news_bind/%EC%BD%94%EC%82%AC%EC%9D%B8%EC%9C%A0%EC%82%AC%EB%8F%84_%EA%B8%B0%EB%B0%98_%EC%B6%94%EC%B2%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 코사인유사도 추천 결과 확인

In [43]:
import pandas as pd
from datetime import datetime, timedelta

In [44]:
data = pd.read_csv("/content/drive/MyDrive/BKBS/news_bind.csv")
data

,context_id,title,source,published,code,context
0,464098,"익산 서부권역 다목적 체육관, 다음달 개관",전북일보,2021-03-25,스포츠,익산시 서부권역 다목적 체육관이 내달 개관을 앞두고 막바지 개관 준비가 한창이다. ...
1,464131,"무주군건강가정·다문화가족지원센터, '아빠하고 나하고' 프로그램 운영",전북일보,2021-03-25,지역,무주군건강가정ㆍ다문화가족지원센터(센터장 장진원)가 아버지와 자녀를 대상으로 ‘아빠하...
2,464132,양희은의 '뜻밖의 만남',전북일보,2021-03-25,문화,양희은의 노래 <엄마가 딸에게>는 엄마와 딸이 차마 말하지 못하는 속마음을 서로에게...
3,464133,전북 산업단지 대개조 지역경제 도약 기회로,전북일보,2021-03-25,IT과학,"군산ㆍ익산ㆍ완주지역의 노후 산업단지에 내년부터 3년간 국비와 지방비, 민간자본 등 ..."
4,464134,익산 함라면 야산서 불… 신원 미상 남성 시신 1구 발견,전북일보,2021-03-25,사회,25일 오전 11시 35분께 익산시 함라면의 한 야산에서 불이 나 1시간 30분만에...
...,...,...,...,...,...,...
144011,1121886,“5월9일 밤∼10일 새벽 부천 ‘메리트나이트’ 방문자는 코로나19 검사 요청”,세계일보,2020-05-18,사회,이태원 클럽 방문 확진자 1명이 감염력이 있는 기간에 부천 지역 유흥시설을 방문한 ...
144012,1121892,"'이태원 클럽' 확진자, 부천 나이트클럽도 방문…지역감염 확산 우려",세계일보,2020-05-18,사회,이태원 클럽을 다녀온 뒤 신종 코로나바이러스 감염증(코로나19)에 감염된 환자 중 ...
144013,1121893,"동국제약, 코로나19 진정 효과 ‘포폴주사’ 주요 4개국 수출",세계일보,2020-05-18,IT과학,"동국제약(대표이사 오흥주)은 네덜란드, 룩셈부르크, 싱가폴, 일본 등 유럽과 아시아..."
144014,1121895,"송가인, 5·18 민주화운동 희생자 추모 “영원히 잊지 않을 것”",세계일보,2020-05-18,지역,트로트 가수 송가인이 5·18 민주화운동 희생자들을 추모했다. \n\n송가인은 18...
144015,1121904,"딸 출산한 류현진-배지현 공식 입장 “코로나로 어려운 상황이지만, 감사하고 행복하다”",세계일보,2020-05-18,스포츠,미국 프로야구 메이저리그에서 활약하는 류현진(33·토론토 블루제이스)과 전 아나운서...

In [45]:
data['published'] = pd.to_datetime(data['published'], format="%Y-%m-%d")

article = data.loc[:, ['context_id', 'title', 'context', 'published', 'source']]
article

,context_id,title,context,published,source
0,464098,"익산 서부권역 다목적 체육관, 다음달 개관",익산시 서부권역 다목적 체육관이 내달 개관을 앞두고 막바지 개관 준비가 한창이다. ...,2021-03-25,전북일보
1,464131,"무주군건강가정·다문화가족지원센터, '아빠하고 나하고' 프로그램 운영",무주군건강가정ㆍ다문화가족지원센터(센터장 장진원)가 아버지와 자녀를 대상으로 ‘아빠하...,2021-03-25,전북일보
2,464132,양희은의 '뜻밖의 만남',양희은의 노래 <엄마가 딸에게>는 엄마와 딸이 차마 말하지 못하는 속마음을 서로에게...,2021-03-25,전북일보
3,464133,전북 산업단지 대개조 지역경제 도약 기회로,"군산ㆍ익산ㆍ완주지역의 노후 산업단지에 내년부터 3년간 국비와 지방비, 민간자본 등 ...",2021-03-25,전북일보
4,464134,익산 함라면 야산서 불… 신원 미상 남성 시신 1구 발견,25일 오전 11시 35분께 익산시 함라면의 한 야산에서 불이 나 1시간 30분만에...,2021-03-25,전북일보
...,...,...,...,...,...
144011,1121886,“5월9일 밤∼10일 새벽 부천 ‘메리트나이트’ 방문자는 코로나19 검사 요청”,이태원 클럽 방문 확진자 1명이 감염력이 있는 기간에 부천 지역 유흥시설을 방문한 ...,2020-05-18,세계일보
144012,1121892,"'이태원 클럽' 확진자, 부천 나이트클럽도 방문…지역감염 확산 우려",이태원 클럽을 다녀온 뒤 신종 코로나바이러스 감염증(코로나19)에 감염된 환자 중 ...,2020-05-18,세계일보
144013,1121893,"동국제약, 코로나19 진정 효과 ‘포폴주사’ 주요 4개국 수출","동국제약(대표이사 오흥주)은 네덜란드, 룩셈부르크, 싱가폴, 일본 등 유럽과 아시아...",2020-05-18,세계일보
144014,1121895,"송가인, 5·18 민주화운동 희생자 추모 “영원히 잊지 않을 것”",트로트 가수 송가인이 5·18 민주화운동 희생자들을 추모했다. \n\n송가인은 18...,2020-05-18,세계일보
144015,1121904,"딸 출산한 류현진-배지현 공식 입장 “코로나로 어려운 상황이지만, 감사하고 행복하다”",미국 프로야구 메이저리그에서 활약하는 류현진(33·토론토 블루제이스)과 전 아나운서...,2020-05-18,세계일보

In [46]:
article[article['title'].str.contains("배터리 자립")]['title'].item()

'배터리 자립 선언하는 車업계… “어느 세월에” 속내는 착잡'

In [47]:
# 기준 기사
base_article = {
    "title": article[article['title'].str.contains("배터리 자립")]['title'].item(),
    "context": article[article['title'].str.contains("배터리 자립")]['context'].item(),
    "published": article[article['title'].str.contains("배터리 자립")]['published'].item(),
    "source": article[article['title'].str.contains("배터리 자립")]['source'].item()
}
base_article

{'title': '배터리 자립 선언하는 車업계… “어느 세월에” 속내는 착잡',
 'context': '미국 자동차 시장 점유율 1위 포드의 최고경영자(CEO) 짐 팔리는 최근 한 포럼에서 전기차 시장에서 살아남기 위해 ‘배터리 내재화’가 필요하다고 강조했다. 그로부터 약 일주일 뒤 곧바로 배터리 자체 생산 계획을 공식화했다. 디트로이트에 1억8500만 달러(2060억원)를 들여 배터리 연구·개발센터인 ‘포드이온파크’를 설립하고, 리튬이온 배터리를 자체 개발할 예정이다. \n \n글로벌 완성차 업계의 ‘배터리 권력’ 쟁탈전이 뜨겁다. 폭스바겐, 제너럴모터스(GM)에 이어 포드까지 배터리 내재화를 공식 선언했다. \n \n배터리 자체 생산으로 원가 절감 효과를 보지 못한다면 미래 전기차 시장에서 도태될 수 있다는 위기감이 반영된 결과다. \n \n다만 업계의 무게 중심이 내연기관 엔진에서 배터리와 반도체로 개편되고 있다는 점이 부담이다. ‘전기차의 심장’이라 불리는 배터리가 협력 업체에서 개발이 이뤄진다면 완성차 업체가 기대하는대로 기존의 원·하청 수직 관계가 유지되기 어렵다는 관측이 나오고 있어서다. 전기차 배터리는 장기간 개발이 이뤄져야 양산이 가능하다는 점도 리스크 요인으로 꼽힌다. \n \n세계 1위 완성차 업체인 폭스바겐은 최근 2030년까지 유럽 내 배터리 공장 6곳을 증설해 연간 240GWh 배터리 셀을 만들겠다고 밝혔다. 블룸버그에 따르면 유럽의 전기차 배터리 관련 지원금은 1년 사이 10배 증가한 61억 유로(8조900억원)에 이른다. \n \nGM은 자체 생산보다는 배터리 전문 업체인 LG에너지솔루션과 협업을 선택했다. LG와의 합작법인인 ‘얼티엄셀즈’를 설립하고 미 오하이오주에 연 30GWh 규모의 배터리 공장을 짓고 있다. 향후 테네시주에도 두 번째 공장을 들이기로 했다. 테슬라와 현대자동차 역시 배터리 자체 생산을 추진하겠다고 발표한 바 있다. \n \n배터리 내재화 바람은 전기차 배터리의 높은 원가가 그 배경에 있다. 전기차 가격에서 배터리 생산에 들어가는 비중은 30~40% 달한다. \n \n다만 업계 안팎에서는 완성차 업체의 배터리 내재화가 쉽지만은 않을 것이라는 전망이 지배적이다. 폭스바겐의 경우 유럽 내 ‘리딩 배터리 기업’이 존재하지 않다는 점이 협업을 다소 망설이게 한다. 관련 시장 점유율은 사실상 한국과 중국, 일본 등이 나누어 가진 상태기 때문이다. \n \n배터리 양산까지 상당한 시간이 필요하다는 점도 고민거리다. \n \n김필수 대림대 자동차학과 교수는 2일 “전기차 배터리는 내구도나 안정성 등 민감한 이슈가 많아 자체 개발까지 최대 20년까지 걸릴 수 있다”고 설명했다. 완성차 업계의 잇단 ‘배터리 자립’ 선언에 관련 업계가 냉소적인 시선을 보내는 이유기도 하다. \n \n가장 심각한 것은 내연기관을 만드는 전통 완성차 업계의 지위가 흔들리고 있다는 점이다. 업계 권력이 엔진에서 배터리·반도체로 넘어가는 와중에 원청 역할만 수행하던 완성차 업체로서는 배터리 업체를 하청처럼 부릴 수 없게 됐다. 수직적 분업 관계가 수평적 분업 관계로 재편되면 자체 배터리 개발에 나선 신생 전기차 빅테크 기업에 비해 비용 절감 효과를 보지 못할 가능성이 크다. \n ',
 'published': Timestamp('2021-05-03 00:00:00'),
 'source': '국민일보'}

In [48]:
# 기준일 ±30일 범위의 기사만 후보로
time_window = 30
start_date = base_article['published'] - timedelta(days=time_window)
end_date = base_article['published'] + timedelta(days=time_window)

candidate_articles = article[
    (article['published'] >= start_date) &
    (article['published'] <= end_date)
].reset_index(drop=True)
if 'context_id' in candidate_articles.columns and 'context_id' in base_article:
    candidate_articles = candidate_articles[candidate_articles['context_id'] != base_article['context_id']]
else:
    # context_id 없으면 제목 기준 제외
    candidate_articles = candidate_articles[candidate_articles['title'] != base_article['title']]

In [49]:
candidate_articles.head()

,context_id,title,context,published,source
0,467658,"김제 진봉면 지역사회보장협의체, 착한 가게 현판 전달",김제시 진봉면(면장 오승영) 지역사회보장협의체(위원장 박영현)는 2일 이웃 사랑에 ...,2021-06-02,전북일보
1,467660,"군산시 ""지방세 스마트폰으로 간편하게 납부하세요""",군산시가 시민들이 편리하게 지방세를 납부할 수 있도록 안내를 진행하고 있다고 2일 ...,2021-06-02,전북일보
2,467661,"전북도, 코로나19 장기화 어려움 겪는 문화예술인 추가 지원",전북도가 코로나19 장기화로 어려움을 겪는 지역 문화예술인을 위해 5억5000만 원...,2021-06-02,전북일보
3,467662,"전북서 코로나19 7명 확진, 누적 2246명",전북도 방역당국은 2일 전북에서 코로나19 신규 확진자가 7명이 발생해 누적 확진자...,2021-06-02,전북일보
4,467663,"한국환경공단 전북환경본부·전북농협, 탄소중립 달성 상호 협약",한국환경공단 전북환경본부(본부장 정재웅)와 전북농협(본부장 정재호)은 지난달 31일...,2021-06-02,전북일보

In [50]:
candidate_articles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41546 entries, 0 to 41546
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   context_id  41546 non-null  int64
 1   title       41546 non-null  object
 2   context     41546 non-null  object
 3   published   41546 non-null  datetime64[ns]
 4   source      41546 non-null  object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 1.9+ MB

In [51]:
## 텍스트 임베딩
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

# 기준 기사 벡터
base_text = base_article['title'] + " " + base_article['context']
base_embedding = model.encode(base_text, convert_to_tensor=True)

# 후보 기사 벡터
candidate_texts = candidate_articles['title'] + " " + candidate_articles['context']
candidate_embeddings = model.encode(candidate_texts.tolist(), convert_to_tensor=True)

In [52]:
## 유사도 계산

cos_scores = util.pytorch_cos_sim(base_embedding, candidate_embeddings)[0]
candidate_articles['similarity'] = cos_scores.cpu().numpy()

In [53]:
top5 = candidate_articles.sort_values(by='similarity', ascending=False).head(5)
print(top5[['title', 'context', 'published', 'source', 'similarity']])

                                             title  \
33771        글로벌 기업도 못 피해가는 불매운동... 소비자는 '진심'을 원한다
29949  '車반도체 품귀 막자'... 홍남기 "차량용 반도체 예산, 내년 대폭 늘린다"
38037              “에너지 사용 미쳤다” 머스크 또 트윗…도지코인 띄우기?
30559                  파나소닉, 테슬라 이외의 배터리 사업 다각화 강조
36501             ‘쓰미마셍, 우리도 없어요~’ 일본도 뜻밖의 車반도체 난리

                                                 context  published source  \
33771  불매운동은 글로벌 기업들도 피해가지 못한다. 올해 1분기 세계 전기차 시장 판매량 ... 2021-05-31   한국일보
29949  정부가 차량용 반도체 수급 부족 문제를 해결하기 위해 단기간 내 사업화할 수 있는 ... 2021-04-16   한국일보
38037  테슬라 최고경영자(CEO) 일론 머스크가 비트코인 결제 중단 선언에 이어 영국의 한... 2021-05-14   국민일보
30559  세계 최대 EV 배터리 생산 업체 중 하나인 파나소닉의 CEO, 쓰가 가즈히로(Ts... 2021-04-14   한국일보
36501  정부가 최근 일본의 반도체 제조사 르네사스에 차량용 반도체 지원 요청을 한 것으로 ... 2021-06-02   국민일보

       similarity
33771    0.871962
29949    0.862631
38037    0.861510
30559    0.857370
36501    0.854153

## 함수화

In [36]:
import pandas as pd
from datetime import timedelta
from sentence_transformers import SentenceTransformer, util

data = pd.read_csv("/content/drive/MyDrive/BKBS/news_bind.csv")
data.head()

,context_id,title,source,published,code,context
0,464098,"익산 서부권역 다목적 체육관, 다음달 개관",전북일보,2021-03-25,스포츠,익산시 서부권역 다목적 체육관이 내달 개관을 앞두고 막바지 개관 준비가 한창이다. ...
1,464131,"무주군건강가정·다문화가족지원센터, '아빠하고 나하고' 프로그램 운영",전북일보,2021-03-25,지역,무주군건강가정ㆍ다문화가족지원센터(센터장 장진원)가 아버지와 자녀를 대상으로 ‘아빠하...
2,464132,양희은의 '뜻밖의 만남',전북일보,2021-03-25,문화,양희은의 노래 <엄마가 딸에게>는 엄마와 딸이 차마 말하지 못하는 속마음을 서로에게...
3,464133,전북 산업단지 대개조 지역경제 도약 기회로,전북일보,2021-03-25,IT과학,"군산ㆍ익산ㆍ완주지역의 노후 산업단지에 내년부터 3년간 국비와 지방비, 민간자본 등 ..."
4,464134,익산 함라면 야산서 불… 신원 미상 남성 시신 1구 발견,전북일보,2021-03-25,사회,25일 오전 11시 35분께 익산시 함라면의 한 야산에서 불이 나 1시간 30분만에...

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144016 entries, 0 to 144015
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   context_id  144016 non-null  int64
 1   title       144016 non-null  object
 2   source      144016 non-null  object
 3   published   144016 non-null  object
 4   code        144016 non-null  object
 5   context     144016 non-null  object
dtypes: int64(1), object(5)
memory usage: 6.6+ MB

In [39]:
data['published'] = pd.to_datetime(data['published'], format="%Y-%m-%d")

In [41]:
def recommend_articles_by_cosine(base_article, articles_df, top_n=5, time_window=30):
    """
    기준 기사와 유사한 기사를 추천하는 함수

    Parameters:
    - base_article: dict, {"title": str, "content": str, "published": datetime, "source": str}
    - articles_df: pd.DataFrame, ['context_id', 'title', 'source', 'published', 'code', 'context']
    - top_n: int, 추천할 기사 수
    - time_window: int, 기준일 ±일 범위로 후보 필터링

    Returns:
    - pd.DataFrame: 상위 N개 추천 기사 ['title', 'context', 'published', 'source', 'similarity']
    """
    articles_df['published'] = pd.to_datetime(data['published'], format="%Y-%m-%d")
    articles_df = articles_df.loc[:, ['context_id', 'title', 'context', 'published', 'source']]

    # 1. 후보 기사 필터링 (출판일 기준)
    start_date = base_article['published'] - timedelta(days=time_window)
    end_date = base_article['published'] + timedelta(days=time_window)

    candidate_articles = articles_df[
        (articles_df['published'] >= start_date) &
        (articles_df['published'] <= end_date)
    ].reset_index(drop=True)

    # 기준 기사 제외
    if 'context_id' in articles_df.columns and 'context_id' in base_article:
        candidate_articles = candidate_articles[candidate_articles['context_id'] != base_article['context_id']]
    else:
        # context_id 없으면 제목 기준 제외
        candidate_articles = candidate_articles[candidate_articles['title'] != base_article['title']]

    if candidate_articles.empty:
        return pd.DataFrame(columns=['title', 'content', 'publish_date', 'similarity'])

    # 2. 텍스트 임베딩
    model = SentenceTransformer('all-MiniLM-L6-v2')
    base_text = base_article['title'] + " " + base_article['context']
    base_embedding = model.encode(base_text, convert_to_tensor=True)

    candidate_texts = candidate_articles['title'] + " " + candidate_articles['context']
    candidate_embeddings = model.encode(candidate_texts.tolist(), convert_to_tensor=True)

    # 3. 유사도 계산
    cos_scores = util.pytorch_cos_sim(base_embedding, candidate_embeddings)[0]
    candidate_articles['similarity'] = cos_scores.cpu().numpy()

    # 4. 상위 N개 추천
    top_articles = candidate_articles.sort_values(by='similarity', ascending=False).head(top_n)

    return top_articles[['title', 'context', 'published', 'source', 'similarity']]

In [42]:
# 기준 기사
base_article = {
    "title": article[article['title'].str.contains("배터리 자립")]['title'].item(),
    "context": article[article['title'].str.contains("배터리 자립")]['context'].item(),
    "published": article[article['title'].str.contains("배터리 자립")]['published'].item(),
    "source": article[article['title'].str.contains("배터리 자립")]['source'].item()
}
base_article

{'title': '배터리 자립 선언하는 車업계… “어느 세월에” 속내는 착잡',
 'context': '미국 자동차 시장 점유율 1위 포드의 최고경영자(CEO) 짐 팔리는 최근 한 포럼에서 전기차 시장에서 살아남기 위해 ‘배터리 내재화’가 필요하다고 강조했다. 그로부터 약 일주일 뒤 곧바로 배터리 자체 생산 계획을 공식화했다. 디트로이트에 1억8500만 달러(2060억원)를 들여 배터리 연구·개발센터인 ‘포드이온파크’를 설립하고, 리튬이온 배터리를 자체 개발할 예정이다. \n \n글로벌 완성차 업계의 ‘배터리 권력’ 쟁탈전이 뜨겁다. 폭스바겐, 제너럴모터스(GM)에 이어 포드까지 배터리 내재화를 공식 선언했다. \n \n배터리 자체 생산으로 원가 절감 효과를 보지 못한다면 미래 전기차 시장에서 도태될 수 있다는 위기감이 반영된 결과다. \n \n다만 업계의 무게 중심이 내연기관 엔진에서 배터리와 반도체로 개편되고 있다는 점이 부담이다. ‘전기차의 심장’이라 불리는 배터리가 협력 업체에서 개발이 이뤄진다면 완성차 업체가 기대하는대로 기존의 원·하청 수직 관계가 유지되기 어렵다는 관측이 나오고 있어서다. 전기차 배터리는 장기간 개발이 이뤄져야 양산이 가능하다는 점도 리스크 요인으로 꼽힌다. \n \n세계 1위 완성차 업체인 폭스바겐은 최근 2030년까지 유럽 내 배터리 공장 6곳을 증설해 연간 240GWh 배터리 셀을 만들겠다고 밝혔다. 블룸버그에 따르면 유럽의 전기차 배터리 관련 지원금은 1년 사이 10배 증가한 61억 유로(8조900억원)에 이른다. \n \nGM은 자체 생산보다는 배터리 전문 업체인 LG에너지솔루션과 협업을 선택했다. LG와의 합작법인인 ‘얼티엄셀즈’를 설립하고 미 오하이오주에 연 30GWh 규모의 배터리 공장을 짓고 있다. 향후 테네시주에도 두 번째 공장을 들이기로 했다. 테슬라와 현대자동차 역시 배터리 자체 생산을 추진하겠다고 발표한 바 있다. \n \n배터리 내재화 바람은 전기차 배터리의 높은 원가가 그 배경에 있다. 전기차 가격에서 배터리 생산에 들어가는 비중은 30~40% 달한다. \n \n다만 업계 안팎에서는 완성차 업체의 배터리 내재화가 쉽지만은 않을 것이라는 전망이 지배적이다. 폭스바겐의 경우 유럽 내 ‘리딩 배터리 기업’이 존재하지 않다는 점이 협업을 다소 망설이게 한다. 관련 시장 점유율은 사실상 한국과 중국, 일본 등이 나누어 가진 상태기 때문이다. \n \n배터리 양산까지 상당한 시간이 필요하다는 점도 고민거리다. \n \n김필수 대림대 자동차학과 교수는 2일 “전기차 배터리는 내구도나 안정성 등 민감한 이슈가 많아 자체 개발까지 최대 20년까지 걸릴 수 있다”고 설명했다. 완성차 업계의 잇단 ‘배터리 자립’ 선언에 관련 업계가 냉소적인 시선을 보내는 이유기도 하다. \n \n가장 심각한 것은 내연기관을 만드는 전통 완성차 업계의 지위가 흔들리고 있다는 점이다. 업계 권력이 엔진에서 배터리·반도체로 넘어가는 와중에 원청 역할만 수행하던 완성차 업체로서는 배터리 업체를 하청처럼 부릴 수 없게 됐다. 수직적 분업 관계가 수평적 분업 관계로 재편되면 자체 배터리 개발에 나선 신생 전기차 빅테크 기업에 비해 비용 절감 효과를 보지 못할 가능성이 크다. \n ',
 'published': Timestamp('2021-05-03 00:00:00'),
 'source': '국민일보'}

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/BKBS/news_bind.csv")
data

,context_id,title,source,published,code,context
0,464098,"익산 서부권역 다목적 체육관, 다음달 개관",전북일보,20210325,스포츠,익산시 서부권역 다목적 체육관이 내달 개관을 앞두고 막바지 개관 준비가 한창이다. ...
1,464131,"무주군건강가정·다문화가족지원센터, '아빠하고 나하고' 프로그램 운영",전북일보,20210325,지역,무주군건강가정ㆍ다문화가족지원센터(센터장 장진원)가 아버지와 자녀를 대상으로 ‘아빠하...
2,464132,양희은의 '뜻밖의 만남',전북일보,20210325,문화,양희은의 노래 <엄마가 딸에게>는 엄마와 딸이 차마 말하지 못하는 속마음을 서로에게...
3,464133,전북 산업단지 대개조 지역경제 도약 기회로,전북일보,20210325,IT과학,"군산ㆍ익산ㆍ완주지역의 노후 산업단지에 내년부터 3년간 국비와 지방비, 민간자본 등 ..."
4,464134,익산 함라면 야산서 불… 신원 미상 남성 시신 1구 발견,전북일보,20210325,사회,25일 오전 11시 35분께 익산시 함라면의 한 야산에서 불이 나 1시간 30분만에...
...,...,...,...,...,...,...
144011,1121886,“5월9일 밤∼10일 새벽 부천 ‘메리트나이트’ 방문자는 코로나19 검사 요청”,세계일보,20200518,사회,이태원 클럽 방문 확진자 1명이 감염력이 있는 기간에 부천 지역 유흥시설을 방문한 ...
144012,1121892,"'이태원 클럽' 확진자, 부천 나이트클럽도 방문…지역감염 확산 우려",세계일보,20200518,사회,이태원 클럽을 다녀온 뒤 신종 코로나바이러스 감염증(코로나19)에 감염된 환자 중 ...
144013,1121893,"동국제약, 코로나19 진정 효과 ‘포폴주사’ 주요 4개국 수출",세계일보,20200518,IT과학,"동국제약(대표이사 오흥주)은 네덜란드, 룩셈부르크, 싱가폴, 일본 등 유럽과 아시아..."
144014,1121895,"송가인, 5·18 민주화운동 희생자 추모 “영원히 잊지 않을 것”",세계일보,20200518,지역,트로트 가수 송가인이 5·18 민주화운동 희생자들을 추모했다. \n\n송가인은 18...
144015,1121904,"딸 출산한 류현진-배지현 공식 입장 “코로나로 어려운 상황이지만, 감사하고 행복하다”",세계일보,20200518,스포츠,미국 프로야구 메이저리그에서 활약하는 류현진(33·토론토 블루제이스)과 전 아나운서...

In [ ]:
top_articles = recommend_articles_by_cosine(base_article, data)
top_articles

,title,context,published,source,similarity
33771,글로벌 기업도 못 피해가는 불매운동... 소비자는 '진심'을 원한다,불매운동은 글로벌 기업들도 피해가지 못한다. 올해 1분기 세계 전기차 시장 판매량 ...,2021-05-31,한국일보,0.871962
29949,"'車반도체 품귀 막자'... 홍남기 ""차량용 반도체 예산, 내년 대폭 늘린다""",정부가 차량용 반도체 수급 부족 문제를 해결하기 위해 단기간 내 사업화할 수 있는 ...,2021-04-16,한국일보,0.862631
38037,“에너지 사용 미쳤다” 머스크 또 트윗…도지코인 띄우기?,테슬라 최고경영자(CEO) 일론 머스크가 비트코인 결제 중단 선언에 이어 영국의 한...,2021-05-14,국민일보,0.861510
30559,"파나소닉, 테슬라 이외의 배터리 사업 다각화 강조","세계 최대 EV 배터리 생산 업체 중 하나인 파나소닉의 CEO, 쓰가 가즈히로(Ts...",2021-04-14,한국일보,0.857370
36501,"‘쓰미마셍, 우리도 없어요~’ 일본도 뜻밖의 車반도체 난리",정부가 최근 일본의 반도체 제조사 르네사스에 차량용 반도체 지원 요청을 한 것으로 ...,2021-06-02,국민일보,0.854153